### ISSUE TITLE
Clarify documentation to specify where to run `jupyter-o2`?

### ISSUE THREAD

**Issue by alextruong** [AaronKollasch/jupyter-o2#4]
Hi Aaron! Looks like this endeavor is still alive and well! We've pointed a number of users here already, and we haven't gotten any complaints so far, so I'd like to thank you again for setting this up.

Anyway, we actually encountered a ticket recently where a user was having trouble using this repo to make their connections, and it occurred to me that they were attempting to configure their stuff on the cluster directly, as opposed to locally. I'm not sure if this is a wider problem that's solving itself as users debug without our intervention, but perhaps it may be good to specify that you should be installing jupyter-o2 _locally_, and running the command to create the session _locally_? There's some weirdness that pops up when you try to run this from a login node, for example, but it's probably not worth investigating because that's an incorrect use case for this anyway. Anyway, just a thought. Thanks again!

-Alex

**Comment by aaronkollasch** [comment]
Hi Alex! I'm glad it mostly seems to be working and other users are finding it helpful. 

I've updated the readme to specify where jupyter-o2 should be installed and run. Thanks for the heads up!

Aaron
