### ISSUE TITLE
SSHError: pxssh error: could not synchronize with original prompt

### ISSUE THREAD

**Issue by preetida** [AaronKollasch/jupyter-o2#5]
Hi, 
so far its been working great, but lately i have issue with jupyter login, it shows; error : 
SSHError: pxssh error: could not synchronize with original prompt

Any clue, what must be going on!

**Comment by aaronkollasch** [comment]
Hi, thanks for your note!
This error most commonly occurs when the O2 ssh server requests two-factor authentication and jupyter-o2 is expecting a normal command-line prompt instead of the authentication prompt. 
If you get 2FA prompts when SSH'ing into O2, you will need to add the arguments `--2fa --2fa-code 1` to your jupyter-o2 command. The first will let jupyter-o2 know to expect 2FA, and the second will tell it to request a Duo push.
Let me know if that works,
-Aaron

**Comment by preetida** [comment]
Thanks for your reply.
This time i tried with 2fa. n here what happens.

(base) Preets-MacBook-Pro:Downloads Pretty$ jupyter-o2 notebook --2fa
--2fa-code 1

Connect to O2 server for jupyter notebook

Enter your passphrase:

Connecting to pjb40@o2.hms.harvard.edu

Hostname: login01.o2.rc.hms.harvard.edu


Starting an interactive session.

srun: job 64537706 queued and waiting for resources

JupyterO2Error: The timeout (60) was reached without receiving a prompt.



If it helps, i have attached my config file here for you to review.

thanks
Preeti

Preetida  J.  Bhetariya, Ph.D.
Bioinformatics Analyst / RA
Bioinformatics Core
Harvard T.H. Chan School of Public Health
http://bioinformatics.sph.harvard.edu/
(M) : 815-909-8373

**Comment by aaronkollasch** [comment]
Hi Preeti,
Looks like the interactive job is taking longer to start than the default timeout (60 seconds).

I will disable this timeout by default in the next release, but in the mean time you can disable it by changing this line in your config: 

    ;START_INTERACTIVE_SESSION_TIMEOUT = -1

to 

    START_INTERACTIVE_SESSION_TIMEOUT = None

**Comment by preetida** [comment]
Ok, It worked this time.
This was very helpful, thank you.
On a completely different note, on memory optimization on O2 for jupyter,
I usually have to give a huge memory for my script to run in notebook,
hence i changed the default mem in config file.
Still the kernel keeps dying on me, when it hits the particular line in
script { for loop for large array},

I am guessing, its a specific script behaviousr with jupyeter and nothing
wrong with how jupyeter is running.
while i am testing this and i would like to use notebook, can you think of
any other way to resolve <not kernel dying >, other than trying with very
small test, and run it on terminal with slurm.

If its not in the scope of jupyter-O2 i completely understand.
Thank you,

Preeti
Preetida  J.  Bhetariya, Ph.D.
Bioinformatics Analyst / RA
Bioinformatics Core
Harvard T.H. Chan School of Public Health
http://bioinformatics.sph.harvard.edu/
(M) : 815-909-8373

**Comment by aaronkollasch** [comment]
Great, I'm glad to hear it worked!

Regarding memory usage, jupyter shouldn't use huge amounts of extra memory compared to an equivalent python script, as long as you don't run the cells that eat up memory more than once without restarting the kernel (this might defeat the purpose of an interactive notebook though). 

For the really memory-intensive or time-consuming jobs I will usually submit a slurm script – the [jupyter bash kernel](https://github.com/takluyver/bash_kernel/) could be useful for keeping a log of those jobs.
