### ISSUE TITLE
New O2 infrastructure for launching Jupyter

### ISSUE THREAD

**Issue by amyyxt** [AaronKollasch/jupyter-o2#6]
There seems to have been an update to the [wiki page for Jupyter on O2](https://wiki.rc.hms.harvard.edu/display/O2/Jupyter+on+O2) dated Jul 20, 2020.

Based on what I remember of the old instructions, the changes include:
1. `--tunnel` flag in the `srun` command to complete the tunnel (for x11 forwarding, presumably)
2. a second terminal ssh'ing into the compute node from (1) is _no longer used_

**Comment by aaronkollasch** [comment]
Looks like a useful addition! That means one less 2FA prompt is needed if you are remote.

In testing, the old way (with a second ssh) still works, but I will add the option to use that flag and not run a second ssh, and make it the default in the config.

**Comment by amyyxt** [comment]
coolio
Thanks!

**Comment by aaronkollasch** [comment]
I've addressed these changes in Jupyter-O2 version 1.0.2. 
The lack of a second ssh should make 2FA a bit less annoying during work from home.

**Comment by amyyxt** [comment]
great! thank you!
